<?php
/**
 * VCC Website Installer
 * A WordPress-like installation script for the VCC informative site
 */

// Prevent direct access if already installed
if (file_exists('config.php')) {
    die('The site is already installed. Delete config.php to reinstall.');
}

$error = '';
$success = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $db_host = trim($_POST['db_host'] ?? 'localhost');
    $db_name = trim($_POST['db_name'] ?? '');
    $db_user = trim($_POST['db_user'] ?? '');
    $db_pass = $_POST['db_pass'] ?? '';
    $site_title = trim($_POST['site_title'] ?? 'Virtual Communication Connection');
    $site_url = trim($_POST['site_url'] ?? '');
    
    // Validate required fields
    if (empty($db_name) || empty($db_user)) {
        $error = 'Database name and username are required.';
    } else {
        // Test database connection
        try {
            $dsn = "mysql:host=$db_host;dbname=$db_name;charset=utf8mb4";
            $pdo = new PDO($dsn, $db_user, $db_pass);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            
            // Create tables if needed
            createTables($pdo);
            
            // Generate config file
            $configContent = generateConfig($db_host, $db_name, $db_user, $db_pass, $site_title, $site_url);
            
            if (file_put_contents('config.php', $configContent)) {
                $success = true;
            } else {
                $error = 'Could not write config.php. Please check file permissions.';
            }
        } catch (PDOException $e) {
            $error = 'Database connection failed: ' . $e->getMessage();
        }
    }
}

function createTables($pdo) {
    // Create contact messages table
    $sql = "CREATE TABLE IF NOT EXISTS contact_messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        subject VARCHAR(255),
        message TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
    
    $pdo->exec($sql);
    
    // Create settings table
    $sql = "CREATE TABLE IF NOT EXISTS settings (
        id INT AUTO_INCREMENT PRIMARY KEY,
        setting_key VARCHAR(100) UNIQUE NOT NULL,
        setting_value TEXT,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
    
    $pdo->exec($sql);
    
    // Insert default settings
    $stmt = $pdo->prepare("INSERT IGNORE INTO settings (setting_key, setting_value) VALUES (?, ?)");
    $stmt->execute(['site_title', 'Virtual Communication Connection']);
    $stmt->execute(['contact_email', 'info@vcc.com']);
    $stmt->execute(['whatsapp_number', '+18095866653']);
}

function generateConfig($db_host, $db_name, $db_user, $db_pass, $site_title, $site_url) {
    $db_pass_escaped = str_replace("'", "\'", $db_pass);
    $site_title_escaped = str_replace("'", "\'", $site_title);
    
    return "<?php
/**
 * VCC Website Configuration File
 * 
 * This file was auto-generated by the installer.
 * Do not edit manually unless you know what you're doing.
 */

// Database Configuration
define('DB_HOST', '$db_host');
define('DB_NAME', '$db_name');
define('DB_USER', '$db_user');
define('DB_PASS', '$db_pass_escaped');

// Site Configuration
define('SITE_TITLE', '$site_title_escaped');
define('SITE_URL', '$site_url');

// Database Connection
function getDBConnection() {
    try {
        \$dsn = \"mysql:host=\" . DB_HOST . \";dbname=\" . DB_NAME . \";charset=utf8mb4\";
        \$pdo = new PDO(\$dsn, DB_USER, DB_PASS);
        \$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        return \$pdo;
    } catch (PDOException \$e) {
        die('Database connection failed: ' . \$e->getMessage());
    }
}

// Security: Prevent direct access to config
if (!defined('VCC_INSTALLED')) {
    define('VCC_INSTALLED', true);
}
";
}

// If installation successful, redirect to site
if ($success) {
    header('Location: index.php');
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VCC Installation</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #0a2540 0%, #00d4d4 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        
        .installer-container {
            background: white;
            border-radius: 15px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
            max-width: 600px;
            width: 100%;
            overflow: hidden;
        }
        
        .installer-header {
            background: #0a2540;
            color: white;
            padding: 40px;
            text-align: center;
        }
        
        .installer-header h1 {
            font-size: 2.5rem;
            margin-bottom: 10px;
        }
        
        .installer-header p {
            opacity: 0.9;
            font-size: 1.1rem;
        }
        
        .installer-body {
            padding: 40px;
        }
        
        .form-group {
            margin-bottom: 25px;
        }
        
        .form-group label {
            display: block;
            margin-bottom: 8px;
            font-weight: 600;
            color: #0a2540;
        }
        
        .form-group input {
            width: 100%;
            padding: 12px 15px;
            border: 2px solid #e0e0e0;
            border-radius: 8px;
            font-size: 1rem;
            transition: border-color 0.3s;
        }
        
        .form-group input:focus {
            outline: none;
            border-color: #00d4d4;
        }
        
        .form-group small {
            display: block;
            margin-top: 5px;
            color: #666;
            font-size: 0.85rem;
        }
        
        .section-title {
            color: #00d4d4;
            font-size: 1.3rem;
            margin: 30px 0 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #e0e0e0;
        }
        
        .btn-install {
            background: linear-gradient(135deg, #0a2540, #00d4d4);
            color: white;
            border: none;
            padding: 15px 40px;
            font-size: 1.1rem;
            font-weight: 600;
            border-radius: 8px;
            cursor: pointer;
            width: 100%;
            transition: transform 0.3s, box-shadow 0.3s;
        }
        
        .btn-install:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 30px rgba(0, 212, 212, 0.3);
        }
        
        .alert {
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 25px;
        }
        
        .alert-error {
            background: #fee;
            color: #c00;
            border-left: 4px solid #c00;
        }
        
        .logo-preview {
            text-align: center;
            margin-bottom: 20px;
        }
        
        .logo-placeholder {
            width: 80px;
            height: 80px;
            background: linear-gradient(135deg, #0a2540, #00d4d4);
            border-radius: 50%;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-weight: bold;
            font-size: 1.5rem;
        }
    </style>
</head>
<body>
    <div class="installer-container">
        <div class="installer-header">
            <div class="logo-preview">
                <div class="logo-placeholder">VCC</div>
            </div>
            <h1>Welcome to VCC</h1>
            <p>Website Installation Wizard</p>
        </div>
        
        <div class="installer-body">
            <?php if ($error): ?>
                <div class="alert alert-error"><?php echo htmlspecialchars($error); ?></div>
            <?php endif; ?>
            
            <form method="POST" action="">
                <div class="section-title">🌐 Site Information</div>
                
                <div class="form-group">
                    <label for="site_title">Site Title</label>
                    <input type="text" id="site_title" name="site_title" value="Virtual Communication Connection" required>
                    <small>The name of your website</small>
                </div>
                
                <div class="form-group">
                    <label for="site_url">Site URL (Optional)</label>
                    <input type="url" id="site_url" name="site_url" placeholder="https://yourdomain.com">
                    <small>Your website address (leave empty for now)</small>
                </div>
                
                <div class="section-title">💾 Database Configuration</div>
                
                <div class="form-group">
                    <label for="db_host">Database Host</label>
                    <input type="text" id="db_host" name="db_host" value="localhost" required>
                    <small>Usually "localhost"</small>
                </div>
                
                <div class="form-group">
                    <label for="db_name">Database Name</label>
                    <input type="text" id="db_name" name="db_name" required>
                    <small>The name of your database</small>
                </div>
                
                <div class="form-group">
                    <label for="db_user">Database Username</label>
                    <input type="text" id="db_user" name="db_user" required>
                    <small>Your MySQL username</small>
                </div>
                
                <div class="form-group">
                    <label for="db_pass">Database Password</label>
                    <input type="password" id="db_pass" name="db_pass">
                    <small>Your MySQL password</small>
                </div>
                
                <button type="submit" class="btn-install">Install VCC Website</button>
            </form>
        </div>
    </div>
</body>
</html>
